SHELL := /bin/bash

build:
	g++ -o matrix_generator matrix_generator.cpp
	g++ -o muliplication multiplication.cpp
#	g++ -fopenmp -o openmp_multiplication openmp_multiplication.cpp

run:
#	./matrix_generator 10 10 >> A.txt
#	./matrix_generator 10 10 >> B.txt
	./muliplication A.txt B.txt
#	./openmp_multiplication